apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-app-container
    image: nginx:latest
    resources:
      requests:
        memory: "256Mi"   # minimum guaranteed RAM
        cpu: "250m"       # 250 millicores = 0.25 CPU
      limits:
        memory: "512Mi"   # max RAM allowed
        cpu: "500m"       # max CPU allowed
