apiVersion: v1
kind: Pod
metadata:
  name: readiness-demo
spec:
  containers:
  - name: demo
    image: busybox
    args:
    - /bin/sh
    - -c
    - |
      echo "App start ho rahi hai..."
      sleep 20
      echo "Ready file bana raha hoon"
      touch /tmp/ready
      echo "App ready hai!"
      sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 5
